// File generated by AntiGravity (Manual Fallback).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Web configuration from Firebase Console
  // Note: For Web, you need to copy the config object from:
  // Firebase Console -> Project Settings -> General -> Your Apps -> Web App -> SDK Setup and Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTWNuwUcefL-5XQLshZRoYjLC4pMucdA', // Usually same as Android
    appId: '1:921795982728:web:b4deed3772cce637e1763d',
    messagingSenderId: '921795982728',
    projectId: 'travel-tourism-6561f',
    authDomain: 'travel-tourism-6561f.firebaseapp.com',
    storageBucket: 'travel-tourism-6561f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTWNuwUcefL-5XQLshZRoYjLC4pMucdA',
    appId: '1:921795982728:android:583ba2e4778f96e5e1763d',
    messagingSenderId: '921795982728',
    projectId: 'travel-tourism-6561f',
    storageBucket: 'travel-tourism-6561f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTWNuwUcefL-5XQLshZRoYjLC4pMucdA',
    appId: '1:921795982728:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '921795982728',
    projectId: 'travel-tourism-6561f',
    storageBucket: 'travel-tourism-6561f.firebasestorage.app',
    iosBundleId: 'com.travel.tourism.travel_tourism',
  );
}
